Feature nab 465/update h2 version
coastland/gsp-dba-maven-plugin pull request #168
Opened 2022-09-22 02:52 UTC by sukegawatakashitis

H2のバージョンを 2.1.210 に更新しました。

jira:
https://nablarch.atlassian.net/browse/NAB-465

redmine:
https://milky.adc-tis.com/redmine/issues/51815

2022-10-04 02:22 UTC, opengl-8080 requested changes

2022-10-04 02:22 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +* Eclpselinkを使った現状の簡易検証では、H2のテストに失敗します。ただし、生成されたソースはDBに依存しないため、必要に応じてH2以外のDBを使って検証を実施してください。
対応漏れ

2022-10-04 02:22 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +        - JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
文章構成に違和感を覚えるので指摘しますが、まず違和感を覚える理由を説明する前提として、私が認識する箇条書きリストの構造について説明します。
（私は箇条書きリストは～～という文書構造を構成するものだと思っているけど、上の文章はそうなっていないから違和感を覚える、という説明をするための前書きです。この前提となる認識そのものに齟齬がある場合はご指摘ください）

私の認識では、箇条書きリストを入れ子で表現する場合、下位のリストは上位のリストの文章を補足するものという認識です。
また、重要度が高い（もっとも伝えたいこと）の方が、リストの上のほうに来るという認識です。
その方が、文章の構成として読みやすい形になるからと考えているからです（結論を述べ、その理由を説明する、という順序は理解しやすい文章になる。また重要度の高い事柄を上に持ってくることで、より伝えたいことを伝えやすくなる）。

**イメージ**

- 結論・一番言いたいこと
  - 理由１（もっとも直接的な理由）
  - 理由２（その他の理由）
  - 補足情報
- 二番目に言いたいこと
  - 補足情報１
    - 補足情報１をさらに補足する情報
  - 補足情報２

この認識の前提で上の箇条書きの文章を読むと、順序が逆に感じるところや言いたいことが表現できていない箇所が多くあり、違和感があります。

冒頭の文章（DBにH2を指定した場合、～）では、一番伝えたいことは「H2の場合はPostgreSQLを代替にしてください」ということだと思います。
すると、この文章を読んだ人は「別のDBでテストしても大丈夫なの？」という疑問を抱くのではないかなと私は思います。
この疑問を払拭するためにも、補足情報として次に出した方が良い情報は「アノテーションの設定はDB製品に依存しないため、JPAの仕様通りであるか確認することが目的ならH2以外のDB製品で確認しても問題ありません。」ではないかなと、思います。

ただ、これだと「アノテーションの設定は～」という話がいきなり出てくるため、スッと話が理解できない恐れがあります（アノテーションって何のこと？となる）。
これに関しては、「gsp-dba-maven-pluginが生成したエンティティに設定されているアノテーションがJPAの仕様通りであることを確認することが、JPA簡易検証の目的です。」の部分をリストの一番上に持ってきて、そもそものJPA簡易テストの説明の前提として置いておけば、自然な流れになるのではないかと思います。

**イメージ**

```
- gsp-dba-maven-pluginが生成したエンティティに設定されているアノテーションがJPAの仕様通りであることを確認することが、JPA簡易検証の目的です。
- DBにH2を指定した場合、JPA簡易検証で使用しているEclipseLinkの2.5.0が、H2の2.x系に未対応のため、テストに失敗します。PostgreSQLを代替に使用して検証を実施してください。
  - アノテーションの設定はDB製品に依存しないため、JPAの仕様通りであるか確認することが目的ならH2以外のDB製品で確認しても問題ありません。
    - JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
```

次に「gsp-dba-maven-pluginは 2022年9月現在、Jakarta EE 9 に未対応です。」の部分ですが、この中で伝えたいことは「JPA実装の最新版ではH2の2.x系に対応している（または対応している可能性がある）が、 gsp-dba-maven-plugin では利用できない」ということだと思います。

現状は、それぞれのライブラリの Jakarta EE 9 への対応状況を並べただけになっています。
このため、何を言いたいのかがぱっと見でよく分からない文章になっていると感じます。

まず最初に、上記の伝えたいことを書き、「なぜ JPA実装の最新版を gsp-dba-maven-plugin では利用できないのか」を説明する形で下位のリストを構成するのがいいのではないかと思います。

**イメージ**

```
  - JPA実装の最新版ではH2の2.x系に対応しているものもあるが、 gsp-dba-maven-plugin では利用できない
    - Hibernate の 6.x 系は H2 の 2.x 系に対応しているが（※要調査）、 Jakarta EE 9 にも対応している
    - gsp-dba-maven-plugin は Jakarta EE 9 に対応していないので、 Hibernate 6.x 系は利用できない
    - EclipseLink 3.x 系も H2 の 2.x 系に対応しているが（※要調査）、Hibernate 同様に Jakarta EE 9 対応が入っているため gsp-dba-maven-plugin では利用できない
```

※要調査の部分は、 H2 2.x に対応している前提での仮の表現にしています。

---

> EclipseLink 3.0以降は、Jakarta EE 9 に対応**されています**。

受動表現なのが気になりました。
対応するかどうかは各ライブラリが能動的に判断して実施していると思うので、「対応しています」とかの方がおさまりがいいように感じます。

2022-10-04 02:22 UTC, opengl-8080 commented on src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/DbTableMetaReaderWithView.java
> +        	if (!StringUtils.equals(typeName, "TABLE") && !StringUtils.equals(typeName, "BASE TABLE")) {
`TABLE` と `BASE TABLE` の2種類をチェックしている理由をコメントに書いておきましょう。
`BASE TABLE` は H2 の 2.x 系用、 `TABLE` はそれ以外の DB 用、という感じで。

2022-10-04 02:31 UTC, opengl-8080 requested changes

2022-10-04 02:31 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +* DBにH2を指定した場合、JPA簡易検証で使用しているEclipseLinkの2.5.0が、H2の2.x系に未対応のため、テストに失敗します。PostgreSQLを代替に使用して検証を実施してください。
H2 で Entity を生成して PostgreSQL でテストする場合、おそらく invoker-plugin の goal の設定を書き換えて実行するような手順が必要になる気がします。

https://github.com/coastland/gsp-dba-maven-plugin/blob/4.5.0/pom.xml#L575-L580

（まず `<goal>test</goal>` をコメントアウトして H2 で実行し、そのあとで `<goal>test</goal>` 以外をコメントアウトして PostgreSQL で実行する、みたいな感じ）

この手順で本当に Entity 生成だけ H2 でテストは PostgreSQL というのを実現できるのか、まずは確認をお願いいします。
そのうえで、この方法で実現できるのであれば、その手順を README に記載お願いします。

2022-10-06 02:10 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +* Eclpselinkを使った現状の簡易検証では、H2のテストに失敗します。ただし、生成されたソースはDBに依存しないため、必要に応じてH2以外のDBを使って検証を実施してください。
Teams でのご指摘についてはこちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/e7b025f3c52beb8db87573a7a50c903377f4a579

2022-10-07 08:24 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        - JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/d711ad05112172a9b75bbaa46e745e93a5969a7b

H2についての記載を、箇条書きの先頭から最後に移動しました。

2022-10-07 08:25 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +* DBにH2を指定した場合、JPA簡易検証で使用しているEclipseLinkの2.5.0が、H2の2.x系に未対応のため、テストに失敗します。PostgreSQLを代替に使用して検証を実施してください。
こちらで手順を追加しました。
https://github.com/coastland/gsp-dba-maven-plugin/commit/d711ad05112172a9b75bbaa46e745e93a5969a7b

2022-10-07 08:37 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/DbTableMetaReaderWithView.java
> +        	if (!StringUtils.equals(typeName, "TABLE") && !StringUtils.equals(typeName, "BASE TABLE")) {
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/a123ddf825300c556482c6c28386605611a8c4ea

2022-10-14 06:06 UTC, opengl-8080 commented on src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/DbTableMetaReaderWithView.java
> +        	if (!StringUtils.equals(typeName, "TABLE") && !StringUtils.equals(typeName, "BASE TABLE")) {
元々の実装がタブとスペースが混じってるのがそもそもイケてないのが問題なのですが、GitHub上で見たときに直後のコードとコメントが大きくずれているのはさすがにちょっと微妙なので、既存コードとインデントを合わせましょう。

ちなみに、既存コード（if文）の直前にあるインデントは、半角スペース8つとタブ1つで構成されてます。

2022-10-14 06:35 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/DbTableMetaReaderWithView.java
> +        	if (!StringUtils.equals(typeName, "TABLE") && !StringUtils.equals(typeName, "BASE TABLE")) {
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/05833c9f50707d7fd1e37f0a5de9ed32709bd26f

2022-10-17 01:28 UTC, opengl-8080 requested changes

2022-10-17 01:28 UTC, opengl-8080 commented on src/test/resources/jp/co/tis/gsp/tools/dba/mojo/ImportSchemaMojo_test/type/h2/ddl/10_CREATE_TYPETEST.sql
> +  TYPE4 CHAR(4),
こちらの変更、JIRAに記載されているもののどれにも該当しないように思えます。
どういう理由による変更でしょうか？

2022-10-17 01:28 UTC, opengl-8080 commented on src/test/resources/jp/co/tis/gsp/tools/dba/mojo/LoadDataMojo_test/type/h2/ddl/10_CREATE_TYPETEST.sql
> +  TYPE4 CHAR(4),
こちらの変更、JIRAに記載されているもののどれにも該当しないように思えます。
どういう理由による変更でしょうか？

2022-10-17 01:29 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +        - JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
新規に指摘しなおしたので、本スレッドはclose

2022-10-17 01:30 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +* DBにH2を指定した場合、JPA簡易検証で使用しているEclipseLinkの2.5.0が、H2の2.x系に未対応のため、テストに失敗します。PostgreSQLを代替に使用して検証を実施してください。
新規にコメントしたので、こちらのスレッドはclose

2022-10-17 01:56 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +* DBにH2を使用する場合、[レガシーモードでJPA簡易検証を実施](#H2のレガシーモードでJPA簡易検証を実施する手順)してください。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/388475489c13b61894172d04b67405aa1bd3e009

2022-10-17 02:21 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        * EclipseLink以外のJPA実装には、Hibernateがありますが、こちらはH2の 2.1.214 に対応していますが、EclipseLink 3.0 と同様にJakarta EE 9 に対応しているため、使用できません。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/59b987d1d78e79f7938fc5637aca7627760d57fe

2022-10-17 02:26 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        * アノテーションの設定はDB製品に依存しないため、JPAの仕様通りであるか確認することが目的ならH2以外のDB製品で確認しても問題ありません。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/fd02c82490878c571604ade58515da8733f75f9e

2022-10-17 03:17 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        * JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/e96ac0ccc8df9bad420738d5e356e81f0beb1a6e

2022-10-17 05:08 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +    ```
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/5d46b83a0e4c7b283eea8ad64d27172089cd3039

2022-10-17 05:15 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/cb3cfbf6efcac5801def787be3c722841d2039ed

2022-10-17 05:36 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/2df0439056f736740d7dbae598d30b6fde57d714

2022-10-17 06:26 UTC, sukegawatakashitis commented on src/test/resources/jp/co/tis/gsp/tools/dba/mojo/ImportSchemaMojo_test/type/h2/ddl/10_CREATE_TYPETEST.sql
> +  TYPE4 CHAR(4),
H2バージョン更新により、テーブル生成時に桁数指定無しの [BINARY型](http://www.h2database.com/html/datatypes.html#binary_type) および [CHAR型](http://www.h2database.com/html/datatypes.html#character_type) のデフォルト桁数が1となったため、4桁の文字を含むINSERT文の実行に失敗するため、CREATE文を修正しました。

JIRAへの記載が漏れていたため、追記しました。

2022-10-17 06:27 UTC, sukegawatakashitis commented on src/test/resources/jp/co/tis/gsp/tools/dba/mojo/LoadDataMojo_test/type/h2/ddl/10_CREATE_TYPETEST.sql
> +  TYPE4 CHAR(4),
https://github.com/coastland/gsp-dba-maven-plugin/pull/168#discussion_r996653737
と同様の対応をしました。

2022-10-18 04:39 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +        * アノテーションの設定はDB製品に依存しないため、JPAの仕様通りであるか確認することが目的ならH2以外のDB製品で確認しても問題ありません。
「DB製品に依存しない（DB製品の違い）」→「レガシーモードで動かす（バージョンの違い）」だと論理がつながっていないと思いました。

下の文章の修正後と同じように、「DB製品やDBのバージョンに依存しないため」とした方が、違和感は少ないと思いました。

2022-10-18 04:42 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +        * JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
> H2の [互換性の特徴](http://www.h2database.com/html/features.html#compatibility) により、モードをレガシーモードにすることで、バージョン 1.x系として動作させることができます。

レガシーモードについて言及しているのは1つ上の文章なので、そちらの下にぶら下げる形にしましょう。
[上の指摘](https://github.com/coastland/gsp-dba-maven-plugin/pull/168#discussion_r997710646)でバージョンについても触れることになると思うので、ぶら下げることに違和感は無くなると思います。

**イメージ**

```
- アノテーションの設定はDB製品やDBのバージョンに依存しないため、JPAの仕様通りであるか確認することが目的ならH2のレガシーモードで確認しても問題ありません。
  - H2の 互換性の特徴 により、モードをレガシーモードにすることで、バージョン 1.x系として動作させることができます。
- JPAの仕様では、基本的にDB製品やDBのバージョンに依存しない形でアノテーションは設定できるようになっています。
```

2022-10-18 04:49 UTC, opengl-8080 requested changes

2022-10-18 04:49 UTC, opengl-8080 commented on doc/mojo-unit-test.md
> +プロキシ環境下で行う場合は、コマンドで指定する [settings.xml](../src/test/resources/settings.xml) にプロキシの設定を追記してください。
ブラウザ上で見たときに読みにくくなっているので、適宜改行を入れましょう。

「`maven-invoker-plugin`プラグインにより実行する[各ゴール](https://github.com/coastland/gsp-dba-maven-plugin/blob/4.5.0/pom.xml#L575-L580)を、mvnコマンドで直接実行します。」

「コマンドプロンプト(Windows)を起動し、以下を実施してください。Linuxの場合、キャレット(^)をバックスラッシュ(\)に読み替えてください。」

「プロキシ環境下で行う場合は、コマンドで指定する [settings.xml](../src/test/resources/settings.xml) にプロキシの設定を追記してください。」

の3つに分けるのがいいのではないかと思います。

2022-10-18 05:51 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        * アノテーションの設定はDB製品に依存しないため、JPAの仕様通りであるか確認することが目的ならH2以外のDB製品で確認しても問題ありません。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/3b3514c45ce1af6684f303409520d4823bd9194a

2022-10-18 05:55 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +        * JPAの仕様では、基本的にDB製品に依存しない形でアノテーションは設定できるようになっています。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/60733cbba6fe8dbb2c115dd0aca092050c4cf840

2022-10-18 05:59 UTC, sukegawatakashitis commented on doc/mojo-unit-test.md
> +プロキシ環境下で行う場合は、コマンドで指定する [settings.xml](../src/test/resources/settings.xml) にプロキシの設定を追記してください。
こちらで対応しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/168/commits/8474d58b5e22ef4ac881bc0ec2ca97dbf4507789

2022-10-18 06:37 UTC, opengl-8080 approved these changes

2022-10-18 06:38 UTC, merged