動作確認済みバージョンを追記しました。
coastland/gsp-dba-maven-plugin pull request #171
Opened 2022-11-29 07:16 UTC by sukegawatakashitis

2023-03-09 11:38 UTC, kumagoro1202 requested changes

2023-03-09 11:38 UTC, kumagoro1202 commented on en/doc/db-status.md
> +#### Operation checked version
Tested versionにしてください。

2023-03-10 00:48 UTC, sukegawatakashitis commented on en/doc/db-status.md
> +#### Operation checked version
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/171/commits/a27710c029d6ed0c2ff44041e31ba39df7e945d8

2023-03-10 00:58 UTC, kumagoro1202 approved these changes

2023-03-10 00:58 UTC, merged