feat: 新しいOracleに対応しました。
coastland/gsp-dba-maven-plugin pull request #177
Opened 2022-12-23 08:32 UTC by sukegawatakashitis

### 変更内容

GSPプラグインがOracle18c以上で動作するように修正しました。

2022-12-26 05:46 UTC, kumagoro1202 requested changes

2022-12-26 06:21 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +	private String specifier;
こちらを参考にしました。
https://docs.oracle.com/cd/E82638_01/jjdbc/data-sources-and-URLs.html#GUID-C4F2CA86-0F68-400C-95DA-30171C9FB8F0

2022-12-26 08:41 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +	private String specifier;
> こちらを参考にしました。
> https://docs.oracle.com/cd/E82638_01/jjdbc/data-sources-and-URLs.html#GUID-C4F2CA86-0F68-400C-95DA-30171C9FB8F0

上記を参考に、specifier を databaseSpecifier に修正しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/ae40ebb96a065f509000dacd44a5e319d6d1e7b0

2022-12-26 08:42 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +		if(url.split(":")[1].equals("oracle")) {
接続識別子をパラメータで渡すよう修正しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/ae40ebb96a065f509000dacd44a5e319d6d1e7b0

2022-12-26 08:43 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
> +					user + "/" + password + specifier,
こちらで修正しました。
https://github.com/coastland/gsp-dba-maven-plugin/commit/ae40ebb96a065f509000dacd44a5e319d6d1e7b0#diff-3ca90602807ec8a7183dbf86270a870eb10f09b70e227221d9a603eeaaaa756eR119

2022-12-26 08:55 UTC, kumagoro1202 commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +	private String specifier;
参考にしているのがJDBCのURLに関するページです。口頭での話でも出ましたがJDBCのURLでの接続文字列とData Pumpにおける接続文字列についての仕様を確認せずに同じものとして扱うのはやめてください。
少なくとも私が見た範囲でspecifierを使っているところはありませんでした。
「oracle connection "identifier" 」で検索すると様々なページがヒットしますが「oracle database "specifier"」で検索しても有用そうなページは少ないです。日本語でも通常指定子（specifier）ではなく識別子（identifier）と呼ぶと思うので`connectIdentifier`などにしてください。

2022-12-26 08:57 UTC, kumagoro1202 commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +		if(url.split(":")[1].equals("oracle")) {
別途指摘して対応済みだった「ImportSchemaとExportSchemaでしか使わないパラメータをAbstractDbaMojoに持たせるのも違和感です。」という指摘を元に戻したのはどういう意図ですか。

2022-12-27 01:42 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +	private String specifier;
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/5473ecddeb251910bd71a31c85f080d0645b266b

2022-12-27 01:56 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +		if(url.split(":")[1].equals("oracle")) {
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/d76ff72e525e9693119bad9d60a794fcd8176295

2022-12-27 03:56 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +	private String specifier;
上記補足します。

> 当初の修正で、AbstractDbaMojoに統合した理由
user, password などのパラメータを受け取っていたので、AbstractDbaMojoで受け取るのことが適切かと考えました。

 
> やっぱりImportSchemaとExportSchemaに分けて修正した理由

artifactIdやversionをパラメータで受け取っている箇所を確認して、(通常のJDBC接続とは)Import,Exportは分けるべきと考え、AbstractDbaMojoではなく、ImportSchemaとExportSchemaに分けました。

2022-12-27 05:11 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +		if(url.split(":")[1].equals("oracle")) {
補足します。

> 別途指摘して対応済みだった「ImportSchemaとExportSchemaでしか使わないパラメータをAbstractDbaMojoに持たせるのも違和感です。」という指摘を元に戻したのはどういう意図ですか。

AbstractDbaMojoに持たせてしまってい理由は、user, password などのパラメータを受け取っていたので、AbstractDbaMojoで受け取るのことが適切かと考えました。
ご指摘の通り、ImportSchemaとExportSchemaでしか使わないパラメータですので、AbstractDbaMojo に持たせないよう修正しました。
その後、誤って元に戻してしまいましたが、再度、AbstractDbaMojo に持たせないよう修正しました。

ImportSchemaとExportSchemaでartifactIdやversionをパラメータで受け取っているため、これらと同様に connectIdentifier を受け取るよう修正しました。

2022-12-27 06:02 UTC, kumagoro1202 requested changes

2022-12-27 06:10 UTC, sukegawatakashitis commented on src/test/resources/jdbc_test.properties
> +oracle.databaseSpecifier=localhost:1521/XEPDB1
コミット漏れです。
こちらでテストしました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/04c842278d96f3a118a81c600b38ab50f759fa0d

2022-12-27 06:22 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java
> +    @Parameter(defaultValue = "${project.connectIdentifier}")
Parameter の理解が足りておらず、この指定でテストが成功しているため、問題ないと誤認していました。
defaultValueの指定は不要のため、削除しました。また、Oracle18cにてテストしました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/7a53b7c687b5d554c8b79ed3ef2f15950f97cac9

2022-12-27 08:04 UTC, kumagoro1202 requested changes

2022-12-27 08:04 UTC, kumagoro1202 commented on src/it/simple-jpa-test/testParentPom.xml
> +						<connectIdentifier>${db.connectIdentifier}</connectIdentifier>
JPA簡易検証ではExportもImportもしないので不要だと思います。
https://github.com/coastland/gsp-dba-maven-plugin/blob/develop/pom.xml#L581-L588

2022-12-27 08:04 UTC, kumagoro1202 commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/AbstractDbaMojo.java
> +
空白の有無しか変更のないクラスは差分に出て来ないようにしてください。
このPRの中で変更がないのに変更したクラスとして見えるのは良くないです。
他のクラスの空白有無の差分も本来はノイズになるので極力起こらないようにして欲しいですが、一旦対応は不要です。

2022-12-27 08:18 UTC, sukegawatakashitis commented on src/it/simple-jpa-test/testParentPom.xml
> +						<connectIdentifier>${db.connectIdentifier}</connectIdentifier>
こちらで修正しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/02ba7dc1ef45bb55d8a0ea35ca7e5cce8066efab

2022-12-27 08:25 UTC, sukegawatakashitis commented on src/main/java/jp/co/tis/gsp/tools/dba/mojo/AbstractDbaMojo.java
> +
すみません。以後気を付けます。
こちらで修正しました。
https://github.com/coastland/gsp-dba-maven-plugin/pull/177/commits/4b1c77bb3bd501e1c4c28fa95ef142e23bc3c8c8

2022-12-27 08:27 UTC, kumagoro1202 approved these changes

2022-12-27 08:27 UTC, merged