OracleについてChangelogに追記しました。
coastland/gsp-dba-maven-plugin pull request #179
Opened 2023-01-05 00:57 UTC by sukegawatakashitis

Oracle18c 以降のバージョンで動作するよう変更した旨を追記しました。

2023-01-05 01:17 UTC, kumagoro1202 requested changes

2023-01-05 01:17 UTC, kumagoro1202 commented on CHANGELOG.md
> +  - 接続記述子の指定ができるように変更しました。
指定できるのは接続記述子に限らないです。接続文字列としてください。

2023-01-05 01:17 UTC, kumagoro1202 commented on CHANGELOG.md
> +  - 接続記述子の指定ができるように変更しました。
接続文字列を必要とするのはexport-schemaとimport-schemaのゴールについてであることを明記してください。

2023-01-05 01:27 UTC, sukegawatakashitis commented on CHANGELOG.md
> +  - 接続記述子の指定ができるように変更しました。
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits

2023-01-05 01:36 UTC, sukegawatakashitis commented on CHANGELOG.md
> +  - 接続記述子の指定ができるように変更しました。
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/00198c88af6b02f37628ab8a9351937ad432dc72

2023-01-05 04:42 UTC, kumagoro1202 requested changes

2023-01-05 04:42 UTC, kumagoro1202 commented on README.md
> +|connectIdentifier| ×    | 接続文字列。Oracle の export-schema と import-schema のゴールで指定が必要になります。<br />export-schema では[データ・ポンプ・エクスポート](https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utili
口頭で伝えた通り、ゴール共通のパラメータはAbstractDbaMojoのプロパティに、各ゴールで個別のパラメータは各ゴールに対応するMojoクラスのパラメータに対応しているため、export-schema、import-schemaそれぞれのゴールのパラメータとして記載してください。

2023-01-05 04:42 UTC, kumagoro1202 commented on README.md
> +|connectIdentifier| ×    | 接続文字列。Oracle の export-schema と import-schema のゴールで指定が必要になります。<br />export-schema では[データ・ポンプ・エクスポート](https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utili
Oracle以外のDBで指定した場合無視されるということを明記してください。

2023-01-05 04:42 UTC, kumagoro1202 commented on README.md
> +|connectIdentifier| ×    | 接続文字列。Oracle の export-schema と import-schema のゴールで指定が必要になります。<br />export-schema では[データ・ポンプ・エクスポート](https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utili
export-schemaとimport-schemaの各ゴールに記載するため見直してくれると思いますが、

最初に「接続文字列」とだけ書いてもよくわからないと思います。「データ・ポンプ・エクスポートユーティリティの起動時に指定する接続文字列」とかの方がいいと思います。
あと例を書くのも要らないです。公式のドキュメントに誘導してください。
https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utility.html#GUID-72973E3D-FC0A-47E8-A62A-6DF8AD83138D

2023-01-05 05:30 UTC, sukegawatakashitis commented on README.md
> +|connectIdentifier| ×    | 接続文字列。Oracle の export-schema と import-schema のゴールで指定が必要になります。<br />export-schema では[データ・ポンプ・エクスポート](https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utili
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/48f35310cf60d67e8328a6049f2f36969080a2fc

2023-01-05 05:30 UTC, sukegawatakashitis commented on README.md
> +|connectIdentifier| ×    | 接続文字列。Oracle の export-schema と import-schema のゴールで指定が必要になります。<br />export-schema では[データ・ポンプ・エクスポート](https://docs.oracle.com/cd/E96517_01/sutil/oracle-data-pump-export-utili
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/48f35310cf60d67e8328a6049f2f36969080a2fc

2023-01-05 05:40 UTC, sukegawatakashitis commented on CHANGELOG.md
> +    接続文字列は Oracle の export-schema と import-schema のゴールで指定する必要があります。
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/bbd5d35570cd8c0b3bf3db54a6561a2bbd41574a

2023-01-05 11:06 UTC, kumagoro1202 requested changes

2023-01-05 11:06 UTC, kumagoro1202 commented on CHANGELOG.md
> +  - ローカルに立ち上げたMySQL8.0に対し、非SSL接続する場合、useSSL と AllowPublicKeyRetrieval オプションを指定する必要がありますが、
MySQLに限定しないでください。MySQLでたまたま事象が発生しただけでJDBCのURLの仕様としては他のDB製品で起きてもおかしくない問題だと思います。汎化してください。
また指定できず"不便"じゃなく、指定したら処理がエラーになります。回避策があるなら"不便"で済みますが回避策がないので適切な言い回しではありません。
「JDBC接続URLに複数のオプションを"&"で繋げたURLを指定した場合、generate-entityのゴールを実行する際、中間ファイルとして生成されるXMLに"&"がそのまま出力されてXMLのパースに失敗していました。複数オプションを指定しても正常に処理できるよう"&"をエスケープして出力するように対応しました。」とかじゃないでしょうか。

2023-01-10 00:32 UTC, sukegawatakashitis commented on CHANGELOG.md
> +  - XML 外部エンティティ (XXE) インジェクションに対しての脆弱性に対応したバージョンに更新しました。
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/326ff473cbac7c593f9e92e247a7f55bfa081598

2023-01-10 00:33 UTC, sukegawatakashitis commented on CHANGELOG.md
> +  - ローカルに立ち上げたMySQL8.0に対し、非SSL接続する場合、useSSL と AllowPublicKeyRetrieval オプションを指定する必要がありますが、
こちらで修正しました。https://github.com/coastland/gsp-dba-maven-plugin/pull/179/commits/326ff473cbac7c593f9e92e247a7f55bfa081598

2023-01-10 00:36 UTC, kumagoro1202 approved these changes

2023-01-10 00:36 UTC, merged